services:
  - type: web
    name: resume-optimizer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true 