services:
  - type: web
    name: resume-optimizer-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m uvicorn asgi:asgi_app --host 0.0.0.0 --port $PORT --workers 2 --timeout-keep-alive 120 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: WEB_CONCURRENCY
        value: "2"
    healthCheckPath: /
    autoDeploy: true 