services:
  - type: web
    name: resume-optimizer-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app --bind 0.0.0.0:$PORT --log-level info --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 2"
    healthCheckPath: /api/health
    autoDeploy: true 